version: "3.8"

services:
  server:
    image: amruthpillai/reactive-resume:server-latest
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - TURBO_TOKEN=
    restart: always
    ports:
      - 3100:3100
    environment:
      - PUBLIC_URL=
      - PUBLIC_SERVER_URL=
      - PUBLIC_GOOGLE_CLIENT_ID=
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - SECRET_KEY=change-me-to-something-secure
      - POSTGRES_HOST=my-rds-instance.cj0df8ohbzns.us-east-1.rds.amazonaws.com
      - POSTGRES_PORT=5432
      - POSTGRES_SSL_CERT=
      - JWT_SECRET=change-me-to-something-secure
      - JWT_EXPIRY_TIME=604800
      - GOOGLE_CLIENT_SECRET=
      - GOOGLE_API_KEY=
      - MAIL_FROM_NAME=Reactive Resume
      - MAIL_FROM_EMAIL=noreply@rxresu.me
      - MAIL_HOST=
      - MAIL_PORT=
      - MAIL_USERNAME=
      - MAIL_PASSWORD=
      - STORAGE_BUCKET=
      - STORAGE_REGION=
      - STORAGE_ENDPOINT=
      - STORAGE_URL_PREFIX=
      - STORAGE_ACCESS_KEY=
      - STORAGE_SECRET_KEY=
      - PDF_DELETION_TIME=

  client:
    image: amruthpillai/reactive-resume:client-latest
    build:
      context: .
      dockerfile: ./client/Dockerfile
      args:
        - TURBO_TOKEN=
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - server
    environment:
      - PUBLIC_URL=
      - PUBLIC_SERVER_URL=
      - PUBLIC_GOOGLE_CLIENT_ID=
